name: cmip6_derived_cloud_datasets
channels: 
    - conda-forge
dependencies:
    - python
    - dask
    - zarr
    - distributed
    - cmip6_preprocessing
    - coiled
    - xarray
    - intake-esm
    - prefect
    - click
#     - ipykernel
#     - ipywidgets
#     - rechunker
#     - matplotlib
#     - dask-gateway
    