name: Test Flow with conda Env
on: [push]
jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    strategy:
       matrix:
         source_id: ["CanESM5", "GFDL-ESM4", "GFDL-CM4"]
    name: Build (${{ matrix.source_id }})
    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2.1.6
      env:
        # Increase this value to reset cache if ci/environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v2
      with: 
        activate-environment: cmip6_derived_cloud_datasets
        auto-update-conda: false
        channels: conda-forge
        mamba-version: '*'
        channel-priority: strict
        python-version: 3.9
        environment-file: environment.yml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: Check enviroment
      run: conda list
    - name: Login to Coiled
      run: coiled login -a ${{ secrets.COILED_USER }} -t ${{ secrets.COILED_TOKEN }}
    - name: Run Script
      run: python production_test_env.py --source_id=${{matrix.source_id}}
#     - name: Setup upterm session
#       uses: lhotari/action-upterm@v1
#     - name: Install package
#       run: python -m pip install -e . --no-deps --force-reinstall
